#!/usr/bin/env bash
#
# The one supported way to run the integration suite.
#
# It scrubs whatever a previous run left behind, brings a disposable stack up, runs PHPUnit on the host against it, and
# tears the stack down again. A run which fails or is interrupted never leaves a stack behind in an unknown state.
#
# @package    AkeebaRemoteCLI
# @copyright  Copyright (c)2008-2026 Nicholas K. Dionysopoulos / Akeeba Ltd
# @license    GNU General Public License version 3, or later

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${HERE}/../.." && pwd)"

cd "${HERE}"

# ---------------------------------------------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------------------------------------------

if [[ ! -f .env ]]; then
	echo "==> Creating .env from env.dist"
	cp env.dist .env
fi

# shellcheck disable=SC1091
set -a; source ./.env; set +a

PHP_VERSION="${E2E_PHP_VERSION:-8.5}"
PHP_MATRIX="${E2E_PHP_MATRIX:-8.2 8.3 8.4 8.5}"

RUN_MATRIX=0
SKIP_BUILD=0
KEEP_CONTAINERS=0
DOWN_ONLY=0
RUN_TESTS=1
FILTER=""

usage()
{
	cat <<'USAGE'
Usage: run.sh [options]

  --php <version>     Run Remote CLI under this PHP version (default: E2E_PHP_VERSION from .env).
  --matrix            Run the suite once under every PHP version in E2E_PHP_MATRIX.
  --filter <pattern>  Passed straight through to PHPUnit.
  --skip-build        Reuse the Docker images as they are instead of rebuilding them.
  --keep-containers   Leave the stack up afterwards, and reuse it if it is already up.
  --down              Tear the stack down and exit.
  --no-tests          Bring the stack up and provision it, but do not run the suite.
  -h, --help          This message.

With no options: scrub, build, bring the stack up, run the whole suite under the default PHP version, tear down.
USAGE
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		--php)             PHP_VERSION="$2"; shift 2 ;;
		--php=*)           PHP_VERSION="${1#*=}"; shift ;;
		--matrix)          RUN_MATRIX=1; shift ;;
		--filter)          FILTER="$2"; shift 2 ;;
		--filter=*)        FILTER="${1#*=}"; shift ;;
		--skip-build)      SKIP_BUILD=1; shift ;;
		--keep-containers) KEEP_CONTAINERS=1; shift ;;
		--down)            DOWN_ONLY=1; shift ;;
		--no-tests)        RUN_TESTS=0; shift ;;
		-h|--help)         usage; exit 0 ;;
		*)                 echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
	esac
done

compose()
{
	docker compose "$@"
}

scrub()
{
	echo "==> Scrubbing any previous stack"
	compose down --volumes --remove-orphans --timeout 5 >/dev/null 2>&1 || true
}

stack_is_up()
{
	[[ -n "$(compose ps --status running --quiet web 2>/dev/null)" ]] \
		&& [[ -n "$(compose ps --status running --quiet cli 2>/dev/null)" ]]
}

# A run which dies partway must not leave the stack behind. --keep-containers is the one deliberate exception.
cleanup()
{
	if [[ "${KEEP_CONTAINERS}" -eq 1 ]]; then
		echo "==> Leaving the stack up (--keep-containers)."
		echo "    Fixture:   http://127.0.0.1:${E2E_HTTP_PORT:-18090}/"
		echo "    Re-run:    tests/docker/run.sh --keep-containers --skip-build [--filter ...]"
		echo "    Tear down: tests/docker/run.sh --down"

		return
	fi

	echo "==> Tearing the stack down"
	compose down --volumes --remove-orphans --timeout 5 >/dev/null 2>&1 || true
}

if [[ "${DOWN_ONLY}" -eq 1 ]]; then
	scrub
	exit 0
fi

# ---------------------------------------------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------------------------------------------

if ! docker info >/dev/null 2>&1; then
	echo "Docker is not running. Start Docker and try again." >&2
	exit 1
fi

if ! command -v phpunit >/dev/null 2>&1; then
	cat >&2 <<'MISSING'
PHPUnit is not on your PATH.

It is deliberately not a dependency of this project — the PHAR we ship must not carry a test framework inside it — so
install it globally and make sure Composer's global bin directory is on your PATH:

    composer global require phpunit/phpunit
    export PATH="$PATH:$(composer global config bin-dir --absolute)"
MISSING
	exit 1
fi

if [[ ! -f "${PROJECT_ROOT}/remotecli/vendor/autoload.php" ]]; then
	echo "Composer dependencies are not installed. Run 'composer install' in ${PROJECT_ROOT} first." >&2
	exit 1
fi

# The suite reads its connection details from here. It is generated, and git-ignored, so that the committed
# config.dist.php stays the documentation of what the settings are.
write_config()
{
	cat > "${PROJECT_ROOT}/tests/config.php" <<CONFIG
<?php
/**
 * GENERATED by tests/docker/run.sh. Do not edit: your changes will be overwritten on the next run.
 *
 * Edit tests/docker/.env instead, or tests/config.dist.php for the defaults.
 */

return [
	'compose'         => ['docker', 'compose', '--project-directory', '${HERE}'],
	'service'         => 'cli',
	'site'            => 'http://www.example.test',
	'solo'            => 'http://solo.example.test/remote.php',
	'control'         => 'http://127.0.0.1:${E2E_HTTP_PORT:-18090}/control.php',
	'secret'          => '${E2E_SECRET}',
	'token'           => '${E2E_TOKEN}',
	'restrictedToken' => '${E2E_RESTRICTED_TOKEN}',
	'phpVersion'      => '${PHP_VERSION}',
];
CONFIG
}

# ---------------------------------------------------------------------------------------------------------------
# One run, under one PHP version
# ---------------------------------------------------------------------------------------------------------------

run_one()
{
	local php_version="$1"

	echo ""
	echo "============================================================"
	echo "  Akeeba Remote CLI integration suite under PHP ${php_version}"
	echo "============================================================"

	export E2E_PHP_VERSION="${php_version}"
	PHP_VERSION="${php_version}"

	# Reuse a stack only when the user asked to keep it AND to skip the build, and only when it is genuinely up.
	# --keep-containers on its own must still rebuild: the fixture is baked into the image, so reusing the stack after
	# editing it would silently test the previous version of the fixture.
	if [[ "${KEEP_CONTAINERS}" -eq 1 ]] && [[ "${SKIP_BUILD}" -eq 1 ]] && stack_is_up; then
		echo "==> Reusing the stack which is already up"
	else
		scrub

		if [[ "${SKIP_BUILD}" -eq 0 ]]; then
			echo "==> Building images"
			compose build --quiet web cli
		fi

		echo "==> Bringing the stack up"
		compose up --detach --wait web cli
	fi

	# The mounted working copy is owned by the host user; give the CLI container a home it can actually write to.
	compose exec -T cli sh -c 'mkdir -p /home/tester && chmod 0777 /home/tester' >/dev/null

	echo "==> Remote CLI is running under PHP $(compose exec -T cli php -r 'echo PHP_VERSION;')"

	write_config

	if [[ "${RUN_TESTS}" -eq 0 ]]; then
		echo "==> Provisioned. Not running the suite (--no-tests)."

		return 0
	fi

	local -a phpunit_args=(--configuration "${PROJECT_ROOT}/phpunit-integration.xml")

	if [[ -n "${FILTER}" ]]; then
		phpunit_args+=(--filter "${FILTER}")
	fi

	echo "==> Running the suite"
	(cd "${PROJECT_ROOT}" && phpunit "${phpunit_args[@]}")
}

trap cleanup EXIT

if [[ "${RUN_MATRIX}" -eq 1 ]]; then
	failed=""

	for version in ${PHP_MATRIX}; do
		if ! run_one "${version}"; then
			failed="${failed} ${version}"
		fi
	done

	if [[ -n "${failed}" ]]; then
		echo ""
		echo "==> FAILED under PHP:${failed}"
		exit 1
	fi

	echo ""
	echo "==> The whole matrix passed: ${PHP_MATRIX}"

	exit 0
fi

run_one "${PHP_VERSION}"
