<?php
/*
 * @package    AkeebaRemoteCLI
 * @copyright  Copyright (c)2008-2026 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license    GNU General Public License version 3, or later
 */

/**
 * The defaults the integration suite runs with, and the documentation of what its settings are.
 *
 * tests/config.php is what the suite actually reads. It is generated by tests/docker/run.sh from tests/docker/.env and
 * is git-ignored, so this file stays a description rather than drifting into being one.
 */

return [
	// How to reach the container Remote CLI runs in. The suite drives it exactly as a user drives their shell.
	'compose'         => ['docker', 'compose', '--project-directory', __DIR__ . '/docker'],
	'service'         => 'cli',

	// The fixture site, as seen from inside the Compose network.
	'site'            => 'http://www.example.test',
	'solo'            => 'http://solo.example.test/remote.php',

	// The fixture's back door, as seen from the host. Published on the loopback interface by docker-compose.yml.
	'control'         => 'http://127.0.0.1:18090/control.php',

	// The credentials the fixture accepts. Not secret; they never leave the disposable stack.
	'secret'          => 'TheAkeebaBackupSecretWord',
	'token'           => 'c2hhMjU2OjQyOkVYQU1QTEUtVE9LRU4tTk9ULUEtUkVBTC1DUkVERU5USUFMUw==',

	// A token whose Joomla user account may take backups but not download or delete them.
	'restrictedToken' => 'c2hhMjU2OjcxOmRlYWRiZWVmZGVhZGJlZWZkZWFkYmVlZmRlYWRi',

	// The PHP version Remote CLI is running under in the container. Reported by the suite, not enforced by it.
	'phpVersion'      => '8.5',
];
